export const stagesList = [
  {
    item: "Group A",
    id: "GA",
    matches: [
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "5",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "3",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        matchPartsNumber: 2,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "3",
        },
        matchPartsNumber: 3,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Netherland",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "0",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
    ],
    data: [
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 25,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 4,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 24,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Italy",
        },
        points: 23,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "France",
        },
        points: 22,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 2,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Tunisia",
        },
        points: 21,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 3,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Russia",
        },
        points: 20,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "medium" },
      },
    ],
  },
  {
    item: "Group B",
    id: "GB",
    matches: [
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "5",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "3",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        matchPartsNumber: 2,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "3",
        },
        matchPartsNumber: 3,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Netherland",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "0",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
    ],
    data: [
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 25,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 4,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 24,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "bottom" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Italy",
        },
        points: 23,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "France",
        },
        points: 22,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 2,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Tunisia",
        },
        points: 21,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 3,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Russia",
        },
        points: 20,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
    ],
  },
  {
    item: "Group C",
    id: "GC",
    matches: [
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "5",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "3",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        matchPartsNumber: 2,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "3",
        },
        matchPartsNumber: 3,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Netherland",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "0",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
    ],
    data: [
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 25,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 4,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 24,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Italy",
        },
        points: 23,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "France",
        },
        points: 22,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 2,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Tunisia",
        },
        points: 21,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 3,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Russia",
        },
        points: 20,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
    ],
  },
  {
    item: "Group D",
    id: "GD",
    matches: [
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "5",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "3",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        matchPartsNumber: 2,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "3",
        },
        matchPartsNumber: 3,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Netherland",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "0",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
    ],
    data: [
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 25,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 4,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 24,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Italy",
        },
        points: 23,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "France",
        },
        points: 22,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 2,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Tunisia",
        },
        points: 21,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 3,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Russia",
        },
        points: 20,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
    ],
  },
  {
    item: "Group E",
    id: "GF",
    matches: [
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "5",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "3",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "draw",
          goals: "3",
        },
        matchPartsNumber: 2,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Belgium",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "3",
        },
        matchPartsNumber: 3,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
      {
        host: {
          name: "Netherland",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "win",
          goals: "1",
        },
        opponent: {
          name: "Spain",
          flagUrl: "https://olympia.phoinix.ai/pictures/nations/203.png",
          status: "lost",
          goals: "0",
        },
        matchPartsNumber: 1,
        date: "29/06/2021",
        time: "17:00",
        stadium: "Lorem ipsum",
        attendance: "20K",
      },
    ],
    data: [
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 25,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 4,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Switzerland",
        },
        points: 24,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Italy",
        },
        points: 23,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 1,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "France",
        },
        points: 22,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 2,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Tunisia",
        },
        points: 21,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
      {
        rank: 3,
        team: {
          url: "https://olympia.phoinix.ai/pictures/nations/210.png",
          text: "Russia",
        },
        points: 20,
        playedMatches: 12,
        lostMatches: 3,
        wonMatches: 8,
        drawMatches: 1,
        goalFor: 19,
        goalAgainst: 7,
        goalDifference: "+12",
        status: { text: "Qualified", note: "top" },
      },
    ],
  },
];
