// Dummy players
export const playersSpecialStats = [
  {
    player_id: 714,
    player_picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
    player_name_latin: "BEN YEDDER Wissam",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd BEST SCORER WITH WEAKEST FOOT",
    title_fr: "2e MEILLEUR BUTEUR DU MAUVAIS PIED",
    title_ar: "\u0662. MEILLEUR BUTEUR DU MAUVAIS PIED",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 741,
        picture: "https://olympia.phoinix.ai/pictures/players/741.jpg",
        name_latin: "DE BRUYNE Kevin",
        name_arabic: "",
        total: 9,
        main: 0,
      },
      {
        rank: 2,
        id: 714,
        picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
        name_latin: "BEN YEDDER Wissam",
        name_arabic: "",
        total: 9,
        main: 1,
      },
      {
        rank: 3,
        id: 464,
        picture: "https://olympia.phoinix.ai/pictures/players/464.jpg",
        name_latin: "LEWANDOWSKI Robert",
        name_arabic: "",
        total: 8,
        main: 0,
      },
    ],
  },
  {
    player_id: 1222,
    player_picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
    player_name_latin: "DELORT Andy",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd BEST QUICKEST PLAYER TO SCORE A HAT-TRICK",
    title_fr: "2e MEILLEUR JOUEUR LE PLUS RAPIDE \u00c0 MARQUER UN HAT-TRICK",
    title_ar: "\u0662. MEILLEUR ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 431,
        picture: "https://olympia.phoinix.ai/pictures/players/431.jpg",
        name_latin: "SCHICK Patrik",
        name_arabic: "",
        total: "418s",
        main: 0,
      },
      {
        rank: 2,
        id: 1222,
        picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
        name_latin: "DELORT Andy",
        name_arabic: "",
        total: "466s",
        main: 1,
      },
      {
        rank: 3,
        id: 714,
        picture: "https://olympia.phoinix.ai/pictures/players/714.jpg",
        name_latin: "BEN YEDDER Wissam",
        name_arabic: "",
        total: "615s",
        main: 0,
      },
    ],
  },
  {
    player_id: 1222,
    player_picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
    player_name_latin: "DELORT Andy",
    player_name_arabic: "",
    rank: 2,
    rank_en: "2nd",
    rank_fr: "2e",
    rank_ar: "\u0662.",
    title_en: "2nd QUICKEST PLAYER TO SCORE A HAT-TRICK",
    title_fr: "2e LE PLUS RAPIDE JOUEUR \u00c0 MARQUER UN TRIPL\u00c9",
    title_ar: "\u0662. LE PLUS RAPIDE ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 692,
        picture: "https://olympia.phoinix.ai/pictures/players/692.jpg",
        name_latin: "BENZEMA Karim",
        name_arabic: "",
        total: "11",
        main: 0,
      },
      {
        rank: 2,
        id: 1222,
        picture: "https://olympia.phoinix.ai/pictures/players/1222.jpg",
        name_latin: "DELORT Andy",
        name_arabic: "",
        total: "9",
        main: 1,
      },
      {
        rank: 3,
        id: 264,
        picture: "https://olympia.phoinix.ai/pictures/players/264.jpg",
        name_latin: "ARNAUTOVIC Marko",
        name_arabic: "",
        total: "7",
        main: 0,
      },
    ],
  },
  {
    player_id: 571,
    player_picture: "https://olympia.phoinix.ai/pictures/players/571.jpg",
    player_name_latin: "CORREA Joaquin",
    player_name_arabic: "",
    rank: 3,
    rank_en: "3rd",
    rank_fr: "3e",
    rank_ar: "\u0663.",
    title_en: "3rd QUICKEST PLAYER TO SCORE A BRACE",
    title_fr: "3e LE PLUS RAPIDE JOUEUR \u00c0 MARQUER UN DOUBL\u00c9",
    title_ar: "\u0663. LE PLUS RAPIDE ",
    competition_en: "IN TOP 5 LEAGUES",
    competition_fr: "DANS LES CHAMPIONNATS DU TOP 5",
    competition_ar: "",
    standings: [
      {
        rank: 1,
        id: 2048,
        picture: "https://olympia.phoinix.ai/pictures/players/2048.jpg",
        name_latin: "BERGWIJN Steven",
        name_arabic: "",
        total: "78s",
        main: 0,
      },
      {
        rank: 2,
        id: 431,
        picture: "https://olympia.phoinix.ai/pictures/players/431.jpg",
        name_latin: "SCHICK Patrik",
        name_arabic: "",
        total: "104s",
        main: 0,
      },
      {
        rank: 3,
        id: 571,
        picture: "https://olympia.phoinix.ai/pictures/players/571.jpg",
        name_latin: "CORREA Joaquin",
        name_arabic: "",
        total: "118s",
        main: 1,
      },
    ],
  },
];
export const players = [
  {
    key: 0,
    url: "https://olympia.phoinix.ai/pictures/players/23.jpg",
    name: "Liva0",
    additionalInfo: {
      title: "Karim Ben Zima",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Messi", goals: 9 },
        { rank: 2, name: "Cristiano Ronaldo", goals: 7 },
        { rank: 3, name: "Mbapee", goals: 4 },
      ],
    },
  },
  {
    key: 1,
    url: "https://olympia.phoinix.ai/pictures/players/60.jpg",
    name: "Liva1",
    additionalInfo: {
      title: "Livandowski",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Livandowski", goals: 9 },
        { rank: 2, name: "Mohamed Salah", goals: 7 },
        { rank: 3, name: "Sadio Mane", goals: 4 },
      ],
    },
  },
  {
    key: 2,
    url: "https://olympia.phoinix.ai/pictures/players/11.jpg",
    name: "Liva2",
  },
  {
    key: 3,
    url: "https://olympia.phoinix.ai/pictures/players/15.jpg",
    name: "Liva3",
  },
];
//Dummy clubs
export const clubs = [
  {
    key: 0,
    url: "https://olympia.phoinix.ai/pictures/clubs/23.png",
    name: "Liva0",
    additionalInfo: {
      title: "Karim Ben Zima",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Messi", goals: 9 },
        { rank: 2, name: "Cristiano Ronaldo", goals: 7 },
        { rank: 3, name: "Mbapee", goals: 4 },
      ],
    },
  },
  {
    key: 1,
    url: "https://olympia.phoinix.ai/pictures/clubs/60.png",
    name: "Liva1",
    additionalInfo: {
      title: "Livandowski",
      description: "BEST SOCCER WITH WEAKEST FOOT",
      link: { url: "", text: "IN TOP 5 LEAGUES" },
      top3: [
        { rank: 1, name: "Livandowski", goals: 9 },
        { rank: 2, name: "Mohamed Salah", goals: 7 },
        { rank: 3, name: "Sadio Mane", goals: 4 },
      ],
    },
  },
  {
    key: 2,
    url: "https://olympia.phoinix.ai/pictures/clubs/11.png",
    name: "Liva2",
  },
  {
    key: 3,
    url: "https://olympia.phoinix.ai/pictures/clubs/15.png",
    name: "Liva3",
  },
];
export const mostValuablePlayer = {
  player_id: 0,
  player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
  player_name: "LEAO Rafael",
  rating: 9.2,
  goalkeeper: false,
  attribute_1_name: "Goals",
  attribute_1_cardinality: "Total",
  attribute_1_value: 12,
  attribute_1_type: "int",
  attribute_1_unity: "",
  attribute_2_name: "Assists",
  attribute_2_cardinality: "Total",
  attribute_2_value: 10,
  attribute_2_type: "int",
  attribute_2_unity: "",
  attribute_3_name: "Dribbles",
  attribute_3_cardinality: "Per Game",
  attribute_3_value: 3,
  attribute_3_type: "float",
  attribute_3_unity: "",
  attribute_4_name: "Accurate Passes",
  attribute_4_cardinality: "Total",
  attribute_4_value: 72,
  attribute_4_type: "float",
  attribute_4_unity: "%",
};
export const mostValuableGoalKeeper = {
  player_id: 0,
  player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
  player_name: "MAIGNAIN Mike",
  rating: 9.2,
  goalkeeper: false,
  attribute_1_name: "Clean Sheets",
  attribute_1_cardinality: "Total",
  attribute_1_value: 14,
  attribute_1_type: "int",
  attribute_1_unity: "",
  attribute_2_name: "Saves",
  attribute_2_cardinality: "Total",
  attribute_2_value: 202,
  attribute_2_type: "int",
  attribute_2_unity: "",
  attribute_3_name: "Goals Conceded",
  attribute_3_cardinality: "Total",
  attribute_3_type: "int",
  attribute_3_value: 22,
  attribute_3_unity: "",
  attribute_4_name: "Accurate Long Passes",
  attribute_4_cardinality: "Total",
  attribute_4_value: 62,
  attribute_4_type: "float",
  attribute_4_unity: "%",
};
export const tot = [
  {
    position: "GK",
    grid: "0,4",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "MAIGNAIN Mike",
    rating: 9.2,
    goalkeeper: true,
  },
  {
    position: "RB",
    grid: "1,1",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "ARNOLD Alexander",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "LB",
    grid: "1,7",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "CANCELO Joao",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "CD-R",
    grid: "1,3",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "VAN DIJK Birgil",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "CD-L",
    grid: "1,5",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "DIAS Ruben",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "CM-R",
    grid: "3,2",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "MODRIC Luka",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "CM",
    grid: "3,4",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "KIMMIC Joshua",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "CM-L",
    grid: "3,6",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "DE BRUYNE Kevin",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "RW",
    grid: "4,1",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "SALAH Mohamed",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "LW",
    grid: "4,7",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "LEAO Rafael",
    rating: 9.2,
    goalkeeper: false,
  },
  {
    position: "ST",
    grid: "5,4",
    player_id: 0,
    player_picture: "https://olympia.phoinix.ai/pictures/players/0.jpg",
    player_name: "BENZEMA Karim",
    rating: 9.2,
    goalkeeper: false,
  },
];
export default { players, clubs, mostValuableGoalKeeper, mostValuablePlayer };
