export const menu = [
  {
    "name_en": "International Competitions",
    "name_fr": "Comp\u00e9titions Internationales",
    "name_ar": "",
    "editions": [
      {
        "id": 1,
        "link": "https://olympia.phoinix.ai/edition/1/",
        "name_en": "EURO 2020",
        "name_fr": "EURO 2020",
        "name_ar": "",
      },
      {
        "id": 2,
        "link": "https://olympia.phoinix.ai/edition/2/",
        "name_en": "Copa America 2021",
        "name_fr": "Copa America 2021",
        "name_ar": "",
      },
      {
        "id": 13,
        "link": "https://olympia.phoinix.ai/edition/13/",
        "name_en": "Nations League 2021",
        "name_fr": "Ligue des Nations 2021",
        "name_ar": "",
      },
      {
        "id": 14,
        "link": "https://olympia.phoinix.ai/edition/14/",
        "name_en": "AFCON 2021",
        "name_fr": "CAN 2021",
        "name_ar": "",
      },
    ],
  },
  {
    "name_en": "Clubs Competitions",
    "name_fr": "Comp\u00e9titions des Clubs",
    "name_ar": "",
    "editions": [
      {
        "id": 3,
        "link": "https://olympia.phoinix.ai/edition/3/",
        "name_en": "UEFA Champions League",
        "name_fr": "UEFA Ligue des Champions",
        "name_ar": "",
      },
      {
        "id": 4,
        "link": "https://olympia.phoinix.ai/edition/4/",
        "name_en": "UEFA Europa League",
        "name_fr": "UEFA Ligue Europa",
        "name_ar": "",
      },
      {
        "id": 5,
        "link": "https://olympia.phoinix.ai/edition/5/",
        "name_en": "UEFA Europa Conference League",
        "name_fr": "UEFA Ligue Europa Conf\u00e9rence",
        "name_ar": "",
      },
      {
        "id": 6,
        "link": "https://olympia.phoinix.ai/edition/6/",
        "name_en": "UEFA Super Cup",
        "name_fr": "UEFA Super Coupe",
        "name_ar": "",
      },
      {
        "id": 12,
        "link": "https://olympia.phoinix.ai/edition/12/",
        "name_en": "FIFA Club World Cup",
        "name_fr": "FIFA Coupe du Mondes des Clubs",
        "name_ar": "",
      },
    ],
  },
  {
    "name_en": "Leagues",
    "name_fr": "Championnats",
    "name_ar": "",
    "editions": [
      {
        "id": 7,
        "link": "https://olympia.phoinix.ai/edition/7/",
        "name_en": "Premier League",
        "name_fr": "Premier League",
        "name_ar": "",
      },
      {
        "id": 8,
        "link": "https://olympia.phoinix.ai/edition/8/",
        "name_en": "Serie A",
        "name_fr": "Serie A",
        "name_ar": "",
      },
      {
        "id": 9,
        "link": "https://olympia.phoinix.ai/edition/9/",
        "name_en": "La Liga",
        "name_fr": "La Liga",
        "name_ar": "",
      },
      {
        "id": 10,
        "link": "https://olympia.phoinix.ai/edition/10/",
        "name_en": "Bundesliga",
        "name_fr": "Bundesliga",
        "name_ar": "",
      },
      {
        "id": 11,
        "link": "https://olympia.phoinix.ai/edition/11/",
        "name_en": "Ligue 1",
        "name_fr": "Ligue 1",
        "name_ar": "",
      },
    ],
  },
];
